title: Lady Pepper
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.05004769
  brandStrength: 0.1875
  lightness: 0.0483871
  brandColors:
    - '#fefefe'
    - '#d7dbda'
    - '#8c7c62'
    - '#500001'
    - '#875018'
  rhythmicContrast: 0.205371
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: ladypepper
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.29747
layout_spectrum: 0.90504
