name: ladypepper
favicon: null
layout_spectrum: 0.90504
typography_spectrum: 0.29747
title: Lady Pepper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d7dbda'
    - '#8c7c62'
    - '#500001'
    - '#875018'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.050047688418999314
  rhythmicContrast: 0.2053709621541202
purpose: []
